import Script from 'next/script';
import { ThemeProvider } from "./context/ThemeProvide"

import "./globals.css";
import { Footer, Navbar } from './components';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          // defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen bg-white dark:bg-nft-dark">
            <Navbar />
            <div className="pt-65">
              {children}
            </div>
            <Footer />
          </div>

          <Script src="https://kit.fontawesome.com/536146d1a6.js" crossorigin="anonymous" />
        </ThemeProvider>
      </body>
    </html>
  );
}
